### ISSUE TITLE
Add in certificate expiry check

### ISSUE THREAD

**Issue by rossdargan** [rossdargan/hass-config#2]

**Comment by rossdargan** [comment]
2017-05-25 10:31:28 ERROR (MainThread) [homeassistant.helpers.entity] Update for binary_sensor.certificate_nearly_expired fails
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity.py", line 222, in async_update_ha_state
    yield from self.async_update()
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 210, in coro
    res = func(*args, **kw)
  File "/usr/src/app/homeassistant/components/binary_sensor/template.py", line 133, in async_update
    self._state = self._template.async_render().lower() == 'true'
  File "/usr/src/app/homeassistant/helpers/template.py", line 99, in async_render
    return self._compiled.render(kwargs).strip()
  File "/usr/local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
TypeError: '<' not supported between instances of 'str' and 'int'
